### ISSUE TITLE
Question: Will there be 1.12.2?

### ISSUE THREAD

**Issue by TFTWPhoenix** [MineGame159/meteor-client#54]
Will there be 1.12.2? I want to be able to use this (or a slightly modified version of this) on Constantiam or 2b2t.

**Comment by TFTWPhoenix** [comment]
Oh rip just read the website. =(

**Comment by squidoodly** [comment]
We will not be porting this to 1.12.2 forge but we are attempting to implement multiconnect so you will be able to use the client on older versions.

**Comment by TFTWPhoenix** [comment]
oh awesome
looking forward to that
