### ISSUE TITLE
Issue on ./gradlew runClient

### ISSUE THREAD

**Issue by TFTWPhoenix** [MineGame159/meteor-client#55]
Running the gradle task runClient via:
```
> ./gradlew runClient
```

Crashed while initializing the game.
Heres the crash report https://pastebin.pl/view/4cf9302b

Oh and `./gradlew build` works fine. Its just the runClient thats failing.

**Comment by MineGame159** [comment]
I think this is fixed, try it with latest commits.

**Comment by TFTWPhoenix** [comment]
Yep just as you said that I tried and it works! Thanks!
