### ISSUE TITLE
BedAura not placing correctly

### ISSUE THREAD

**Issue by supakeks** [MineGame159/meteor-client#80]
BedAura isn't placing correctly. The client should make you place the bed on top of one of the blocks surrounding your opponent. This will force the crawling animation leaving their lower hitboxes exposed. At the moment, BedAura places in random spots and barely deals any damage.
![bruhmomento](https://user-images.githubusercontent.com/70498670/95006700-04b3d780-05d5-11eb-81e5-fd48fbf15d43.png)

**Comment by squidoodly** [comment]
I need you to provide me video evidence of this because I can almost guarantee that whoever you were fighting was using anti bed. I've tested this in a LAN world and it places as expected.

**Comment by supakeks** [comment]
I was testing this on my alt account who did not have antibed on. My place and break range were over 4 blocks and despite me being 2 blocks away from the obsidian, it was attempting to place it somewhere else. However, when I went one block closer, it started placing in the right spot

**Comment by squidoodly** [comment]
Which direction where you two blocks away? I think there is a y limit of 2 blocks up and down. I can change that if it’s an issue/make it a setting.
