### ISSUE TITLE
Feature Idea: AntiGMSP

### ISSUE THREAD

**Issue by TFTWPhoenix** [MineGame159/meteor-client#82]
Hey, I have an idea. AntiGMSP could render players in spectator. Maybe make the head fully visible I don't know. I'm not good enough with render stuff to know how to do this. This could really help on some servers as spying admins enjoy GMSP. (Vanish pots don't make you invisible to the spying admins.)

**Comment by squidoodly** [comment]
This doesn’t work as the server doesn’t send packets for players in spectator. If it did then tracers and esp would already work.
