### ISSUE TITLE
AutoTrap modes (SUGGESTION)

### ISSUE THREAD

**Issue by supakeks** [MineGame159/meteor-client#86]
Modes for AutoTrap that would be nice to have:

- Crystal (leaves the lower hitbox of your opponent exposed so you can crystal them.)
- Bed (leaves the player's top hitbox exposed to then use bedaura on them.
- Full (completely traps the opponent without leaving a single open spot

Another option that would be nice to have: 
- Packet place: Allows you to trap the opponent by placing blocks using packets, allowing you to place those blocks in the air. If this is confusing, the client Badlion+ has a feature called autoTrapBed which places obsidian above the player using packets

This was probably suggested in the discord but wasn't suggested here

also can I get unmuted in the discord :(

**Comment by notseanyay** [comment]
No unmutes
