### ISSUE TITLE
Spam Crash

### ISSUE THREAD

**Issue by TFTWPhoenix** [MineGame159/meteor-client#87]
When you turn on spam without a message added it crashes the client. The only fix I am aware of is either NBT Edit to disable the spam module, or delete the modules config file.

**Comment by MineGame159** [comment]
Or just open the gui in main menu

**Comment by TFTWPhoenix** [comment]
I didn't even know you could do that. Is it just RSHIFT on the main menu?

**Comment by MineGame159** [comment]
Yeah, its in the client literally from the start
